### ISSUE TITLE
Consider moving to Java 8

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#351]
From the [Oracle noticeboard](http://www.oracle.com/technetwork/java/eol-135779.html):

> Auto-update Notice and End of Public Updates for Oracle JDK 7

> As outlined in the Oracle JDK Support Roadmap, after April 2015, Oracle will not post further updates of Java SE 7 to its public download sites. Customers who need continued access to critical bug fixes and security fixes as well as general maintenance for Java SE 7 or older versions can get long term support through Oracle Java SE Support. The process of migrating users from Java 7 to Java 8 through the auto update feature is expected to take place after the January 2015 CPU release.

So Java 7 reaches EOL in April 2015. We should consider installers that are based on Java 8 assuming that they don't introduce too much bloat.

**Comment by ollekullberg** [comment]
bitcoinj still run on Java6 right? But that is usually not a problem, because Java is backwards compatible.

**Comment by gary-rowe** [comment]
Yes, Java 8 is able to read Java 7 byte code and all the way down.

**Comment by gary-rowe** [comment]
We need to be cautious with a move to Java 8 due to a possible "sniff seed" issue problem: #354.

**Comment by gary-rowe** [comment]
The "sniff seed" issue was resolved as a timing problem with temp directories. Java 8 is back on the roadmap.

**Comment by gary-rowe** [comment]
I'd like to propose moving to Java 8 in Release 0.2.

**Comment by jim618** [comment]
Another consideration is the minimum version of OS that will support MBHD using Java 8.

Currently on Mac OS with our bundled 1_70_80 JRE we need Mac OS 1.7.3+. This was releases July 2011. We probably wouldn't want to force users to have a much more recent OS. We still get plenty of Win32 MBHD downloads which is MS Vista.
